"""add meeting source and meeting_bots

Revision ID: 3a732e1e88cc
Revises: b2f1a9c4d3e5
Create Date: 2026-07-09 18:51:19.668853

"""
from alembic import op
import sqlalchemy as sa


revision = '3a732e1e88cc'
down_revision = 'b2f1a9c4d3e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_bots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_bot_id', sa.String(length=128), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('speaker_timeline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_index(op.f('ix_meeting_bots_provider_bot_id'), 'meeting_bots', ['provider_bot_id'], unique=False)
    # server_default backfills existing rows (adding a NOT NULL column to a
    # populated table otherwise fails on Postgres).
    op.add_column(
        'meetings',
        sa.Column('source', sa.String(length=20), nullable=False, server_default='upload'),
    )
    op.add_column('meetings', sa.Column('calendar_event_id', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_meetings_calendar_event_id'), 'meetings', ['calendar_event_id'], unique=False)

    # Google Calendar tokens + auto-join preference on users
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('google_scopes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('auto_join', sa.String(length=10), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_join')
    op.drop_column('users', 'google_scopes')
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_refresh_token')
    op.drop_index(op.f('ix_meetings_calendar_event_id'), table_name='meetings')
    op.drop_column('meetings', 'calendar_event_id')
    op.drop_column('meetings', 'source')
    op.drop_index(op.f('ix_meeting_bots_provider_bot_id'), table_name='meeting_bots')
    op.drop_table('meeting_bots')
    # ### end Alembic commands ###
